roomreservation/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rentals/', views.RentalListView.as_view(), name='rentals'),
    path('rentals/<int:pk>', views.RentalDetailView.as_view(), name='rental-detail'),
    path('myreservations/', views.ReservedRoomsByUserListView.as_view(), name='my-reservations'),
]

roomreservation/roomreservation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roomreservation/catalog/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.urls import reverse
from datetime import date

# Create your models here.

class RentalPlace(models.Model):
    """Model representing an hotel."""
    name = models.CharField(max_length=200, help_text="Enter the name of the rental place")
    owner = models.ForeignKey('Owner', on_delete=models.SET_NULL, null=True)
    street = models.CharField(max_length=200, help_text="Enter the name of the street where the place is located")
    city = models.CharField(max_length=50, help_text="Enter the name of the city where the place is located")
    description = models.TextField(max_length=1000, help_text="Enter a brief description of the place")

    def get_absolute_url(self):
        """Returns the url to access a particular room."""
        return reverse('rental-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Room(models.Model):
    """Model representing a room."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular room accross the reservation website")
    rental_place = models.ForeignKey('RentalPlace', on_delete=models.RESTRICT, null=True)
    due_back = models.DateField(null=True, blank=True)
    cost = models.IntegerField(null=True, blank=True, help_text="Enter the cost of the room for one night")
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    is_premium = models.BooleanField(help_text="If the room is for premium clients")

    @property
    def is_overdue(self):
        """Determines if the room reservation is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)
    

    RESERVATION_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'Booked'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=RESERVATION_STATUS,
        blank=True,
        default='d',
        help_text='Room availability')

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.rental_place.name)

class Owner(models.Model):
    """Model representing an owner."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10, unique=True, help_text='000-000-0000 (Without the dashes)')

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

roomreservation/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import RentalPlace, Owner, Room

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_rentals = RentalPlace.objects.all().count()
    num_owners = Owner.objects.all().count()
    num_rooms = Room.objects.all().count()
    num_rooms_available = Room.objects.filter(status__exact='a').count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_rentals': num_rentals,
        'num_rooms': num_rooms,
        'num_rooms_available': num_rooms_available,
        'num_owners': num_owners,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class RentalListView(generic.ListView):
    model = RentalPlace
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(RentalListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

class RentalDetailView(generic.DetailView):
    model = RentalPlace
    paginate_by = 10

class ReservedRoomsByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing rooms reserved by a current user."""
    model = Room
    template_name = 'catalog/room_list_reserved_user.html'
    paginate_by = 5

    def get_queryset(self):
        return (
            Room.objects.filter(client=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )

roomreservation/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'rentals' %}">All Rentals</a></li>
                    <li><a href="">All Owners</a></li>

                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'my-reservations' %}">My Reservations</a></li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %} {% block pagination %} 
                {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages
                            }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %} {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

roomreservation/catalog/templates/catalog/rentalplace_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ rentalplace.name }}</h1>

  <p><strong>Owner:</strong> <a href="">{{ rentalplace.owner }}</a></p> 
  <p><strong>Description:</strong> {{ rentalplace.description }}</p>
  <p><strong>Address:</strong> {{ rentalplace.street }}, {{rentalplace.city}}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Rooms</h4>

    {% for r in rentalplace.room_set.all %}
      <hr>
      <p class="{% if r.status == 'a' %}text-success{% elif r.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ r.get_status_display }}
      </p>
      <p><strong>Cost:</strong> ${{ r.cost }}</p>
      {% if r.is_premium %}
        <div class="alert alert-primary" role="alert">
          This room is reserved for premium members only
        </div>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ r.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

roomreservation/catalog/templates/catalog/rentalplace_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Rentals List</h1>
  {% if rentalplace_list %}
  <ul>
    {% for rental in rentalplace_list %}
      <li>
        <a href="{{ rental.get_absolute_url }}">{{ rental.name }}</a> ({{rental.owner}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no rentals in the system.</p>
  {% endif %}
{% endblock %}

roomreservation/catalog/templates/catalog/room_list_reserved_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Rooms Booked</h1>

    {% if room_list %}
    <ul>

      {% for r in room_list %}
      <li class="{% if r.is_overdue %}text-danger{% endif %}">
        <p>{{ r.rentalplace.name }} ({{ r.due_back }})</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no rooms booked.</p>
    {% endif %}
{% endblock %}

roomreservation/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Room Reservation Website</h1>
    <p>Welcome to RoomReservation, a website designe to help you find a room in different locations for your vacations!</p>
    <h2>Dynamic content</h2>
    <p>The system has the following record counts:</p>
    <ul>
        <li><strong>Rental Places:</strong> {{ num_rentals }}</li>
        <li><strong>Rooms:</strong> {{ num_rooms }}</li>
        <li><strong>Rooms available:</strong> {{ num_rooms_available }}</li>
        <li><strong>Owners:</strong> {{ num_owners }}</li>
    </ul>

    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}